module.exports = {
  SERVER_IP: '54.38.207.246',
  SERVER_NAME: 'https://dpornclassic.co',
  //SERVER_NAME: 'http://localhost:3000',
  categoryList : [
    'Straight',
    'Lesbian',
    'Gay',
    'Hardcore',
    'Threesome',
    'Group',
    'Blow Job',
    'Asian',
    'Arabic',
    'Anal',
    'Ethenic',
    'Transexual',
    'Amateur',
    'Teen'
  ],
  usersAllowedToUpload: [
    'sudguru',
    'pranishg',
    'persefone',
    'muksihs',
    'kassy-cage',
    'bitfook',
    'canadian-vixen',
    'ellie-silk',
    'enarose',
    'foxe',
    'bella27',
    'misscassy',
    'o0pepper0o',
    'presleyhart',
    'nsfwcouple',
    'pupmisfit',
    'themistress',
    'sexyvenezolana',
    'kassy-kage',
    'joey-fancy',
    'royaltifffanpage',
    'n0game',
    'dpornshop'
  ] 
}